import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Review from '../../components/Review';
import Filter from '../../components/Filter';
import Menu from '../../components/Menu';
import axios from "axios";
import { useEffect } from "react";
import { useState } from "react";
import ProductBox from "../../components/comps/ProductBox";
import { useRouter } from "next/router";
import AllbedsBox from "../../components/comps/AllbedsBox";
import SleighbedsBox from "../../components/comps/SleighbedsBox";



const options = [
  { value: 'one', label: 'One' },
  { value: 'two', label: 'Two', className: 'myOptionClassName' }, 
];


function Kendallbed({response}){
  const router = useRouter();
  
  const [size, setSize] = useState("");
  const [maxPrice, setMaxPrice] = useState();
  const [minPrice, setMinPrice] = useState();

  const [images, setimages] = useState("");
  const [imageUrl, setImageUrl] = useState("color1");

  useEffect(() => {


    router.push(`/allbed/kendall?${size ? "size=" + size : ""}${maxPrice ? size ? "&maxPrice=" + maxPrice : "maxPrice=" + maxPrice : ""}${minPrice ? "&minPrice=" + minPrice : ""}${images ? "&color=" + images : ""}`)

  }, [size, maxPrice, minPrice, images])
 
 

  const [items ,setItem]=useState(Menu);
  const filterItem =(cateItem) => {
    const updatedItems = Menu.filter((curElem) => {
      return curElem.category === cateItem;

    });
    setItem(updatedItems);

  }

    return(
        <div style={{fontFamily:"sofia-pro,Helvetica,Arial,sans-serif"}}>
             <Head>
          <title>BedsDivans</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          ></link>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          ></link>
          <link rel="icon" href="/logo (1).png" />
        </Head>

        <Header/>

        
        
          <div className="container">
              <div className="row text-center ">
                  <h1 className="font-weight-bold mt-6" style={{color:"#0e3f70"}}>Kendall Bed Range</h1>
                  <p className="mt-4" style={{fontSize:"17px",fontWeight:"300",color:"#3a356d",fontStyle:"normal"}}>A great night’s sleep starts with the perfect bed, and we can help with that! Not only are our house fabric divan beds ridiculously comfortable, but they’re super stylish too. Available in a variety of fabrics and colours, our range of divan beds will complement any home decor perfectly. We have something to suit everyone.</p>

              </div>

          </div>

          <div className="section mt-10">
        <div className="container">
          
         
        <div className="row">
                  <div className="size-box">
                    <div className="single-box">
                      <a href="#">
                        {" "}
                        <Image
                        priority={true}
                          width={100}
                          height={120}
                          src="/assets/images/DivanBedsicon/Group 477.svg"
                          alt="BedsDivan"
                        />
                      </a>

                      <p
                        className="text-center  mt-2"
                        style={{ color: "#222178" }}
                      >
                        {" "}
                        <b> Single </b>
                      </p>
                    </div>

                    <div className="single-box">
                      <a href="#">
                        {" "}
                        <Image
                        priority={true}
                          width={100}
                          height={120}
                          src="/assets/images/DivanBedsicon/Group 478.svg"
                          alt="BedsDivan"
                        />
                      </a>
                      <p
                        className="text-center  mt-2"
                        style={{ color: "#222178" }}
                      >
                        {" "}
                        <b> Small Double </b>
                      </p>
                    </div>

                    <div className="single-box">
                      <a href="#">
                        <Image
                        priority={true}
                          width={100}
                          height={120}
                          src="/assets/images/DivanBedsicon/Group 479.svg"
                          alt="BedsDivan"
                        />
                      </a>
                      <p
                        className="text-center  mt-2"
                        style={{ color: "#222178" }}
                      >
                        {" "}
                        <b> Double </b>
                      </p>
                    </div>

                    <div className="single-box">
                      <a href="#">
                        <Image
                        priority={true}
                          width={100}
                          height={120}
                          src="/assets/images/DivanBedsicon/Group 480.svg"
                          alt="BedsDivan"
                        />
                      </a>
                      <p
                        className="text-center mt-2"
                        style={{ color: "#222178" }}
                      >
                        <b> King</b>
                      </p>
                    </div>

                    <div className="single-box">
                      <a href="#">
                        <Image
                        priority={true}
                          width={100}
                          height={120}
                          src="/assets/images/DivanBedsicon/Group 481.svg"
                          alt="BedsDivan"
                        />
                      </a>
                      <p
                        className="text-center mt-2"
                        style={{ color: "#222178" }}
                      >
                        <b> Super King</b>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          {/* Filter Tag Start */}
          <div
              className="container mt-4 mb-4 rounded"
              style={{ backgroundColor: "#f2f2f2" }}
            >
              <div className="row" style={{ padding: "10px" }}>
                <div className="col-md-3">
                  <span
                    style={{ marginRight: "0 !important", margin: "0 auto" }}
                  >
                    <select
                      className="dropdown-section"
                      onChange={(e) =>
                        // router.push(`/product/divanbed?size=${e.target.value}`)
                        setSize(e.target.value)
                      }
                    >
                      <option label="Beds" />
                      <option value="2FT 6" label="2 6Feet" />
                      <option value="3FT" label="3Feet" />
                      <option value="4FT" label="4Feet" />
                      <option value="4FT 6" label="4 6Feet" />
                      <option value="5FT" label="5 Feet" />
                      <option value="6FT" label="6 Feet" />
                    </select>
                  </span>
                </div>
                <div className="col-md-3">
                  <span
                    style={{ marginRight: "0 !important", margin: "0 auto" }}

                  >


                    <select className="dropdown-section"
                      onChange={(e) => {
                        // const value = JSON.parse(e.target.value)
                        // setimages(value.images);


                        // setMinPrice(value.minPrice);
                        // router.push(`/product/divanbed?color=${value.images}`)
                        setImageUrl(e.target.value)
                      }}>



                      <option label="Color" />
                      <option value={"color1"} label="Grey Linen" />
                      <option value="color2" label="Grey Suede" />
                      <option value="color3" label="Chenille" />
                      <option value="color4" label="Black Crushed" />

                    </select>



                  </span>
                </div>
                <div className="col-md-3">




                  <span
                    style={{ marginRight: "0 !important", margin: "0 auto" }}
                  >
                    {/* <select className="dropdown-section"
                      onChange={(e) => {
                        const value = JSON.parse(e.target.value)
                        setMaxPrice(value.maxPrice);
                        setMinPrice(value.minPrice);
                        router.push(`/allbed/kendall?maxPrice=${value.maxPrice}&minPrice=${value.minPrice}${router?.query?.size ? "&size=" + router.query.size : ""}&color=${value.images}`)


                      }}>
                      <option label="Price" />
                      <option value={JSON.stringify({ maxPrice: 100, minPrice: 50 })} label="50-100" />
                      <option value={JSON.stringify({ maxPrice: 150, minPrice: 101 })} label="0-100" />
                      <option value={JSON.stringify({ maxPrice: 200, minPrice: 150 })} label="151-200" />
                      <option value={JSON.stringify({ maxPrice: 250, minPrice: 201 })} label="201-250" />
                    </select> */}
                  </span>

                </div>
              </div>
            </div>


          

          
    
          

{/* Product Start */}
<div className="lineproduts-style">
  <div className="container">

  
<div className="row">
                {response.map((item) => {
                  
                  var colorName;
                  switch(imageUrl){
                    case "color1": colorName="Grey Linen";
                    break;
                    case "color2": colorName="Grey Suede";
                    break;
                    case "color3": colorName="Chenille";
                    break;
                    case "color4": colorName="Black Crushed";
                    break;
                  }
                   
  
  
                  return (
                    <SleighbedsBox
                      category={item.category}
                      src={item.images[0][imageUrl].base_url}
                      title={item.product_name}
                      price={item.price}
                      size={item.size}
                      color={[colorName]}
                    />
                  );
                })}
              </div>
              </div>
     </div>


          <div className="container">
              <div className="row text-center ">
                  <h2 className="font-weight-bold mt-6" style={{color:"#0e3f70"}}>What is a linen fabric divan Bed?</h2>
                  <p className="mt-4" style={{fontSize:"18px"}}>When it comes to buying a new bed, a linen fabric divan bed is one of the best choices out there. These box-shaped beds are simple but incredibly practical. A divan bed set consists of a specially designed, firm base and a matching mattress.

The sturdy frame is covered in fabric for an aesthetically pleasing appearance and the bed is usually mounted on castor wheels or you can choose chrome gliders if you have wood or laminate flooring.</p>

              </div>

          </div>

          <div className="container">
              <div className="row text-center ">
                  <h2 className="font-weight-bold mt-6" style={{color:"#0e3f70"}}>Finding the right mattress type for your divan bed</h2>
                  <p className="mt-4" style={{fontSize:"18px"}}>The divan base and the mattress are designed to be used in conjunction with each other to provide comfort and good-quality sleep.

You can also choose which type of mattress you want that will suit you and your sleep pattern. Our beds come with a variety of options, choose from the orthopaedic, pocket, or pillow-top range. 

If you prefer a medium or soft mattress, our orthopaedic or pocket mattresses would be the ideal choice. If you like your mattress to be harder, the pillow top range would be the one for you.</p>

              </div>

          </div>

          <div className="container">
              <div className="row text-center ">
                  <h2 className="font-weight-bold mt-6" style={{color:"#0e3f70"}}>Is the standard option a spring mattress?</h2>
                  <p className="mt-4" style={{fontSize:"18px"}}>These days you have more options than just a spring mattress. Generally, you can use any style with a divan bed, however, some designer brands require a sprung edge base.

Sprung edge divans have springs integrated into the base. These springs act as a giant shock absorber and are very luxurious, taking pressure off the mattress.</p>

              </div>

          </div>

          <div className="container">
              <div className="row text-center ">
                  <h2 className="font-weight-bold mt-6" style={{color:"#0e3f70"}}>Which mattress size is best suited to a Divan base?</h2>
                  <p className="mt-4" style={{fontSize:"18px"}}>This depends on which size base you choose. For example, if you have a king size base you wouldn’t buy a single size mattress as it would be far too small.

Another advantage to divans is that they don’t take up too much space as the bed is only as wide as its mattress.</p>

              </div>

          </div>

          {/* Product End */}
          <br/>
          <br/>
          <Review/>
          <br/>
          <br/>
          <Footer/>


        </div>
    )
}
export default Kendallbed;
export async function getServerSideProps(context) {
  const { query } = context;
  const size = query?.size;

  const category='Kendall Beds Range';

  
  const data = await axios.get(
 
  `${process.env.BASE_URL}/api/allbeds/sleighbed/categories?size=${size}&category=${category}`,
   
  );
  const response = data.data.data;
  return {
    props: { response }, // will be passed to the page component as props
  };
}
